import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import { Header } from 'src/components/Header/Header'
import { Navbar } from 'src/components/Navbar/Navbar'
import { useState } from 'react'
import { DownloadVideo } from 'src/apiCalls/DownloadCall'
import { Downloads } from 'src/components/Downloads/Downloads'
import { VideoType } from 'src/components/Downloads/Downloads.model'

type VideoInfo = {
  videoType: string
  thumbnail: string
  title: string
  channelName: string
  videos: VideoType
}

const TiktokPage: NextPage = () => {
  const [searchTerm, setSearchTerm] = useState('')
  const [videoInfo, setVideoInfo] = useState<VideoInfo>()
  const [error, setError] = useState('')

  const handleSearchInput = (searchTerm: string) => {
    setSearchTerm(searchTerm)
  }

  const handleSearchSubmit = async () => {
    const tiktokURL = searchTerm
    if (!tiktokURL) {
      setError('please enter a valid tiktok url')
      return
    }
    const response = await DownloadVideo('tiktok', `${tiktokURL}`)
    setVideoInfo(response)
    setError('')
  }

  return (
    <Container>
      <Head>
        <title>Muha Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header
        DownloaderType={'TikTok'}
        handleSearchInput={handleSearchInput}
        handleSearchSubmit={handleSearchSubmit}
        searchTerm={searchTerm}
        error={error}
      />
      {videoInfo && (
        <Downloads
          title={videoInfo.title}
          thumbnail={videoInfo.thumbnail}
          videos={videoInfo.videos}
          channelName={videoInfo.channelName}
          videoType={'tiktok'}
        />
      )}
    </Container>
  )
}

const Container = styled.div`
  min-height: 100vh;
  width: 100%;
  max-width: 1440px;
`

export default TiktokPage
