import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import { Header } from 'src/components/Header/Header'
import { Navbar } from 'src/components/Navbar/Navbar'
import { useState } from 'react'
import { DownloadYoutubeVideo } from 'src/apiCalls/YoutubeCall'
import { YoutubeDownload } from 'src/components/Downloads/Youtube/YoutubeDownload'

const Youtube: NextPage = () => {
  const [searchTerm, setSearchTerm] = useState('')
  const [videoInfo, setVideoInfo] = useState()
  const [error, setError] = useState('')

  const handleSearchInput = (searchTerm: string) => {
    setSearchTerm(searchTerm)
  }

  const handleSearchSubmit = async () => {
    const videoId = searchTerm.split('=')[1]
    if (!videoId) {
      setError('please enter a valid youtube url')
      return
    }
    const response = await DownloadYoutubeVideo(`${videoId}`)
    setVideoInfo(response)
    setError('')
  }

  return (
    <Container>
      <Head>
        <title>Muha Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header
        DownloaderType={'Youtube'}
        handleSearchInput={handleSearchInput}
        handleSearchSubmit={handleSearchSubmit}
        searchTerm={searchTerm}
        error={error}
      />
      {videoInfo && <YoutubeDownload Video={videoInfo} />}
    </Container>
  )
}

const Container = styled.div`
  min-height: 100vh;
  width: 100%;
  max-width: 1440px;
`

export default Youtube
